build: false
clone_depth: 1
clone_folder: c:\projects\m3uparser

environment:
    PHP_DIR: C:\tools\php

init:
    - SET PATH=%PHP_DIR%;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET ANSICON=121x90 (121x90)

install:
    - ps: Set-Service wuauserv -StartupType Manual
    - cinst php -y --params "/InstallDir:%PHP_DIR%"
    - cinst composer -y --ia "/DEV=%PHP_DIR%"
    - php -v
    - ccomposer self-update
    - cd %APPVEYOR_BUILD_FOLDER%
    - composer install
    - refreshenv

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - vendor\bin\phpunit
